#!/usr/bin/env bash
set -euo pipefail

export LIGHTRAG_SYNC_URL="${LIGHTRAG_SYNC_URL:-http://127.0.0.1:9621/documents/text}"
export LIGHTRAG_SYNC_TOKEN="${LIGHTRAG_SYNC_TOKEN:-}"
export LIGHTRAG_QUERY_URL="${LIGHTRAG_QUERY_URL:-http://127.0.0.1:9621/query}"
export LIGHTRAG_QUERY_TOKEN="${LIGHTRAG_QUERY_TOKEN:-}"
export LIGHTRAG_SYNC_TIMEOUT_MS="${LIGHTRAG_SYNC_TIMEOUT_MS:-5000}"
export LIGHTRAG_QUERY_TIMEOUT_MS="${LIGHTRAG_QUERY_TIMEOUT_MS:-8000}"
export LIGHTRAG_SYNC_MAX_RETRY="${LIGHTRAG_SYNC_MAX_RETRY:-3}"

echo "Starting MoocHub server with LightRAG integration..."
echo "LIGHTRAG_SYNC_URL=${LIGHTRAG_SYNC_URL}"
echo "LIGHTRAG_QUERY_URL=${LIGHTRAG_QUERY_URL}"

go run main.go
